config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
}

  devise_for :admin, skip: [:passwords] ,controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
}

  root to: 'homes#top'
    get '/' => 'homes#top'
    get '/about' => 'homes#about', as: 'about'

  namespace :public do
    resources :users,  only: [:show, :edit, :update] do
      get '/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
      patch '/withdrawal' => 'users#withdrawal', as: 'withdrawal'
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do
        get :favorites
      end
    end
  end
  
  resources :posts, only: [:new, :index,:show,:edit,:create,:destroy,:update] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'confirm'
    end
  end
  
  get 'searches/search' => "searches#search", as: 'search'
  resources :genres, only: [:index]
  
  namespace :admin do
    get '/top' => 'homes#top', as: 'top'
    get '/add' => 'owners#add', as: 'add'
    post '/admin_create' => 'owners#admin_create', as: "admin_create"
    delete '/admin_destroy/:id' => 'owners#admin_destroy', as: "admin_destroy"
    resources :owners,  only: [:index, :show, :edit, :update]
    resources :genres, except: [:new, :show]
    resources :users, only: [:index, :show, :edit, :update]
    patch "withdrawal/:id" => "users#withdrawal", as: "withdrawal"
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user  
  belongs_to :post
  
  validates :comment, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = @post.id
    @comment.score = Language.get_data(comment_params[:comment]) 
    if @comment.save
      flash[:notice] = 'コメントを投稿しました'
      render :comment
    else
      render 'posts/show'
    end
  end

  def destroy
    Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
    flash[:notice] = '投稿を削除しました'
    @post = Post.find(params[:post_id])  
    render :comment
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p><i class="fas fa-comment"></i>コメント数: <%= post.comments.count %></p>

<% if post.comments.present? %>

<% post.comments.each do |comment| %>
<div class="mb-1">
  <div class="comment">
    <div class="comment-box-1">
      <%= link_to public_user_path(comment.user) do %>
        <%= comment.user.name %>
      <% end %>
    </div>
    <div class="comment-box-2">
      <%= comment.comment %>
    </div>
    <div class="comment-box-3">
      <%= comment.created_at.strftime('%Y/%m/%d') %>
    </div>
    <div class="comment-box-4">
      <% if comment.user == current_user %>
        <%= link_to '消去', post_comment_path(comment.post, comment), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger ml-3", remote: true %>
      <% end %>
      <% if admin_signed_in? %>
        <%= link_to '消去', post_comment_path(comment.post, comment), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger ml-3", remote: true %>
      <% end %>
    </div>
  </div>
    
  <div class="comment-score">
    <% if admin_signed_in? %>
      <p class="sentiment-score">本文の感情分析スコア[<%= comment.score %>]</p>
    <% end %>
  </div>
</div>
<% end %>

<% else %>
  <p>コメントはまだありません</p>
<% end %>

app/views/comments/_form.html.erb
<% if user_signed_in?%>
  <%= form_with(model:[post, comment], local: false) do |f| %>
    <%= f.text_area :comment, rows: '5',placeholder: "コメントをここに", class: "w-100" %>
    <%= f.submit "送信する",class: "btn btn-outline-dark btn-sm" %>
  <% end %>
<% end %>

app/views/comments/comment.js.erb
$("#comments_area").html("<%= j(render 'comments/comment', post: @post, comment: @comment) %>");
<!--フォームを送信したあとにフォームの値を空にする-->
$("textarea").val('');

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>