config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
}

  devise_for :admin, skip: [:passwords] ,controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
}

  root to: 'homes#top'
    get '/' => 'homes#top'
    get '/about' => 'homes#about', as: 'about'

  namespace :public do
    resources :users,  only: [:show, :edit, :update] do
      get '/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
      patch '/withdrawal' => 'users#withdrawal', as: 'withdrawal'
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do
        get :favorites
      end
    end
  end
  
  resources :posts, only: [:new, :index,:show,:edit,:create,:destroy,:update] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'confirm'
    end
  end
  
  get 'searches/search' => "searches#search", as: 'search'
  resources :genres, only: [:index]
  
  namespace :admin do
    get '/top' => 'homes#top', as: 'top'
    get '/add' => 'owners#add', as: 'add'
    post '/admin_create' => 'owners#admin_create', as: "admin_create"
    delete '/admin_destroy/:id' => 'owners#admin_destroy', as: "admin_destroy"
    resources :owners,  only: [:index, :show, :edit, :update]
    resources :genres, except: [:new, :show]
    resources :users, only: [:index, :show, :edit, :update]
    patch "withdrawal/:id" => "users#withdrawal", as: "withdrawal"
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    @genres = Genre.all
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @genres = Genre.all
    @post_like_ranks = Post.joins(:favorites).published.sort {|a,b| b.favorites.size <=> a.favorites.size}.uniq.slice(0, 5)
    @post_comment_ranks = Post.joins(:comments).published.sort {|a,b| b.comments.size <=> a.comments.size}.uniq.slice(0, 5)
  end

  def about
    @genres = Genre.all
  end
  
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/homes/top.html.erb
<div class='container'>
  <div class='row'>
    
  <%= image_tag '管理者トップ.jpg', width: '100%' %>
  
  <div class="mx-auto col-9 my-5">
    <h2 class="text-center">管理者のトップページ</h2>
    
    <div class="mx-auto my-5 ">
      <div class="admin-box my-3">
        <%= link_to admin_add_path do %>
          <%= image_tag '管理者作成.png', size: '100x130' %>
        <% end %>
        <h5 class="ml-5">管理者作成</h5>
      </div>
      
      <div class="admin-box my-3">
        <%= link_to admin_owners_path do %>
          <%= image_tag '管理者作成.png', size: '100x130' %>
        <% end %>
        <h5 class="ml-5">管理者一覧</h5>
      </div>

      <div class="admin-box my-3">
        <%= link_to admin_users_path do %>
          <%= image_tag 'ユーザー一覧.png', size: '110x130' %>
        <% end %>
        <h5 class="ml-5 ">ユーザー一覧</h5>
      </div>

      
      <div class="admin-box my-3">
        <%= link_to posts_path do %>
          <%= image_tag '投稿一覧.png', size: '100x130' %>
        <% end %>
        <h5 class="ml-5">投稿一覧</h5>
      </div>

      <div class="admin-box my-3">
        <%= link_to admin_genres_path do %>
          <%= image_tag 'ジャンル一覧.png', size: '140x130' %>
        <% end %>
        <h5 class="ml-5">ジャンル一覧</h5>
      </div>
    </div>
      
  </div>
    
  </div>
</div>