config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
}

  devise_for :admin, skip: [:passwords] ,controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
}

  root to: 'homes#top'
    get '/' => 'homes#top'
    get '/about' => 'homes#about', as: 'about'

  namespace :public do
    resources :users,  only: [:show, :edit, :update] do
      get '/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
      patch '/withdrawal' => 'users#withdrawal', as: 'withdrawal'
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do
        get :favorites
      end
    end
  end
  
  resources :posts, only: [:new, :index,:show,:edit,:create,:destroy,:update] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'confirm'
    end
  end
  
  get 'searches/search' => "searches#search", as: 'search'
  resources :genres, only: [:index]
  
  namespace :admin do
    get '/top' => 'homes#top', as: 'top'
    get '/add' => 'owners#add', as: 'add'
    post '/admin_create' => 'owners#admin_create', as: "admin_create"
    delete '/admin_destroy/:id' => 'owners#admin_destroy', as: "admin_destroy"
    resources :owners,  only: [:index, :show, :edit, :update]
    resources :genres, except: [:new, :show]
    resources :users, only: [:index, :show, :edit, :update]
    patch "withdrawal/:id" => "users#withdrawal", as: "withdrawal"
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/owners_controller.rb
class Admin::OwnersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genres = Genre.all
    @owners = Admin.all.page(params[:page]).per(10)
  end
  
  def show
    @genres = Genre.all
    @owner = Admin.find(params[:id])
  end

  def edit
    @owner = Admin.find(params[:id])
    render :layout => 'nosidebar'
  end
  
  def update
    @owner = Admin.find(params[:id])
    if @owner.update(admin_params)
      redirect_to admin_owner_path(current_admin), notice: "プロフィールを更新しました."
    else
      render :edit
    end
  end
  
  def add
    @admin = Admin.new
    render :layout => 'nosidebar'
  end
  
  def admin_create

    if @admin = Admin.create!(
      name: params[:admin][:name],#'管理者',
      email: params[:admin][:email],#'test@test.com',
      password: params[:admin][:password]#'testtest',
    )
    
    redirect_to admin_owners_path, notice: "管理者を作成しました."
    
    else
      flash[:notice] = "修正に失敗しました"
      redirect_to admin_owners_path
    end
  end
  
  def admin_destroy
    @owner = Admin.find(params[:id])
    if @owner.destroy
      redirect_to admin_owners_path, notice: "管理者を削除しました."
    else
      flash[:notice] = "削除に失敗しました"
      redirect_to admin_owners_path
    end
  end
  
  
  private
  def admin_params
    params.require(:admin).permit(:name, :email, :introduction, :owner_image)
  end
  
end

app/helpers/admin/owners_helper.rb
module Admin::OwnersHelper
end

app/views/admin/owners/add.html.erb
<div class='container'>
  <div class='row'>
    <div class="mx-auto col-8 mt-4">
      <div class="text-center">
        <h2>管理者作成</h2>
      </div>

      <%= form_with model: [:admin,@admin], url: admin_admin_create_path, id: 'admin', class: 'admin form-inline', local: true do |f| %>
        <% if @admin.errors.any? %>
          <%= @admin.errors.count %>件のエラーが発生しました
        <% end %>
        <%= flash[:error] %>
      
      <div class="form-group col-12 my-4">
        <%= f.label :name,'名前' %>
        <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control col-sm-6 col-md-7' %>
        <% if @admin.errors.include?(:name) %>
          <p style="color: red;"><%= @admin.errors.full_messages_for(:name).first %>
        <% end %>
      </div>
      
      <div class="form-group col-12 md-4">
        <%= f.label :email,'メールアドレス' %>
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control col-sm-6 col-md-7' %>
        <% if @admin.errors.include?(:name) %>
          <p style="color: red;"><%= @admin.errors.full_messages_for(:email).first %>
        <% end %>
      </div>
      
      <div class="form-group col-12 mb-4">
        <%= f.label :password do %>
          パスワード<br>(6文字以上)
        <% end %>
        <%= f.password_field :password, class: 'form-control col-sm-6 col-md-7' %>
        <% if @admin.errors.include?(:password) %>
          <p style="color: red;"><%= @admin.errors.full_messages_for(:password).first %>
        <% end %>
      </div>
      
      <div class="form-group col-12 mb-4">
        <%= f.label :password_confirmation do %>
          パスワード<br>(確認用)
        <% end %>
        <%= f.password_field :password_confirmation, class: 'form-control col-sm-6 col-md-7' %>
        <% if @admin.errors.include?(:password_confirmation) %>
          <p style="color: red;"><%= @admin.errors.full_messages_for(:password_confirmation).first %>
        <% end %>
      </div>

      <div class="formn-group col-12">
        <%= f.submit "管理者作成", data: { confirm: '管理者を作成しますか？' }, class: 'btn btn-primary btn-block col-6 mx-auto' %>
      </div>
      
      <% end %>
    </div>
  </div>
</div>

app/views/admin/owners/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="mx-auto col-8 mt-4">
      <div class="text-center">
        <h2>プロフィール編集</h2>
      </div>
        
      <%= form_with model: [:admin,@owner],url: admin_owner_path, class: "form-inline", local:true do |f| %>
        <% if @owner.errors.any? %>
          <%= @owner.errors.count %>件のエラーが発生しました
        <% end %>
        
        <div class="form-group col-12 my-4">
          <%= f.label :name,'名前' %>
          <%= f.text_field :name, class: 'form-control col-sm-6 col-md-7',placeholder: "名前" %>
          <% if @owner.errors.include?(:name) %>
            <p style="color: red;"><%= @owner.errors.full_messages_for(:name).first %>
          <% end %>
        </div>
      
        <div class="form-group col-12 my-4">
          <%= f.label :email,'メールアドレス' %>
          <%= f.email_field :email, class: 'form-control col-sm-6 col-md-7', placeholder: "sample@example.com" %>
          <% if @owner.errors.include?(:email) %>
            <p style="color: red;"><%= @owner.errors.full_messages_for(:email).first %>
          <% end %>
        </div>
      
        <div class="form-group col-12 mb-4">
          <%= f.label :owner_image, 'プロフィール画像', class: "form-file-label" %>
          <%= f.file_field :owner_image, class: "form-file-button owner_image", accept: 'image/*' %>
        </div>
      
        <div class="form-group col-12 mb-4 text-center">
          <div class="col">
            <%= f.submit "編集内容を保存", class: 'btn btn-success' %>
          </div>
        </div>
        
      <% end %>
      
    </div>
  </div>
</div>

app/views/admin/owners/index.html.erb
<div class='container'>
  <div class='row'>
    
    <div class="mx-auto col-sm-12 col-md-8 col-lg-9 my-5">
      <h1>管理者一覧</h1>
      <table class='table table-hover table-inverse'>
        <tbody>
        <% @owners.each do |owner| %>
          <tr>
            <td class="img-admin-fit-radius"><%= image_tag owner.get_owner_image(100,100) %></td>
            <td>
              <%= link_to owner.name, admin_owner_path(owner) %>
            </td>
            <td>
              <%= link_to admin_admin_destroy_path(owner), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger ml-5" do %>
                削除する <i class="fas fa-trash-alt"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      
      <%= paginate @owners, thema: 'twitter-bootstrap-4' %>
    </div>
    
  </div>
</div>

app/views/admin/owners/show.html.erb
<div class='container'>
  <div class='row'>
    
    <div class="mx-auto col-sm-12 col-md-8 col-lg-9 my-5">
      <div class="text-center">
        <h1>管理人のページ</h1>
      </div>
      
      <div class="text-center mb-3">
        <p class="img-object-fit-radius">
          <%= image_tag @owner.get_owner_image(150,150) %>
        </p>
      </div>
      
      <div class="row">
        <div class="col-9 mx-auto">
          <table class='table'>
            <tr>
	            <th>名前</th>
	            <td><%= @owner.name %></td>
            </tr>
            <tr>
	            <th>メールアドレス</th>
	            <td><%= @owner.email %></td>
            </tr>
          </table>
        </div>
      </div>
      
      <div class='row'>
        <div class="col text-right">
          <%= link_to edit_admin_owner_path(current_admin), class: "btn btn-secondary" do %>
            編集する <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
      </div>
    </div>
    
  </div>
</div>