config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
}

  devise_for :admin, skip: [:passwords] ,controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
}

  root to: 'homes#top'
    get '/' => 'homes#top'
    get '/about' => 'homes#about', as: 'about'

  namespace :public do
    resources :users,  only: [:show, :edit, :update] do
      get '/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
      patch '/withdrawal' => 'users#withdrawal', as: 'withdrawal'
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do
        get :favorites
      end
    end
  end
  
  resources :posts, only: [:new, :index,:show,:edit,:create,:destroy,:update] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'confirm'
    end
  end
  
  get 'searches/search' => "searches#search", as: 'search'
  resources :genres, only: [:index]
  
  namespace :admin do
    get '/top' => 'homes#top', as: 'top'
    get '/add' => 'owners#add', as: 'add'
    post '/admin_create' => 'owners#admin_create', as: "admin_create"
    delete '/admin_destroy/:id' => 'owners#admin_destroy', as: "admin_destroy"
    resources :owners,  only: [:index, :show, :edit, :update]
    resources :genres, except: [:new, :show]
    resources :users, only: [:index, :show, :edit, :update]
    patch "withdrawal/:id" => "users#withdrawal", as: "withdrawal"
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,authentication_keys: [:email]
  
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  has_one_attached :profile_image
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :introduction, length: { maximum: 200 }
  validates :profile_image, presence: false
  validates :password, length: { minimum: 6 }, on: :create
  validates :encrypted_password, presence: true, on: :create
  validates :password, presence: true, on: :create
  
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
  
  
  # ユーザーをフォローする
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  # ユーザーのフォローを外す
  def unfollow(user_id)
   relationships.find_by(followed_id: user_id).destroy
  end
  
  # フォロー確認をおこなう
  def following?(user)
    followings.include?(user)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!, except: [:top]
  before_action :is_matching_login_admin, only: [:update, :edit, ]
  
  def index
    @users = User.all.page(params[:page]).per(10)
    @genres = Genre.all
  end

  def show
    @user = User.find(params[:id])
    @genres = Genre.all
    @posts = @user.posts
    @follow = @user.followings
    @follower = @user.followers
  end

  def edit
    render :layout => 'nosidebar'
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if@user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render :edit
    end
  end
  
  def withdrawal
    @user = User.find(params[:id])
    @user.update(is_deleted: !@user.is_deleted)
    
    if @user.is_deleted
      flash[:notice] = "退会処理を実行いたしました"
      redirect_to admin_users_path
    else
      flash[:notice] = "有効にします"
      redirect_to admin_users_path
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :introduction, :profile_image)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class='container'>
  <div class='row'>
    
    <div class="mx-auto col-sm-12 col-md-8 col-lg-9 my-5">
      <h1>ユーザー一覧</h1>
      <table class='table table-hover table-inverse'>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td class="img-admin-fit-radius"><%= image_tag user.get_profile_image(100,100) %></td>
            <td>
              <%= user.name %>
              <br>
              <br>登録日: <%= user.created_at.strftime('%Y/%m/%d') %>
            </td>
            <td>
              <% if user.is_deleted %>
                退会済み
              <% else %>
                有効
              <% end %>
            </td>
            <td><%= link_to '詳細ページへ',admin_user_path(user.id), class: "user_#{user.id} btn btn-info btn-sm" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      
      <%= paginate @users, thema: 'twitter-bootstrap-4' %>
    </div>
    
  </div>
</div>

app/views/admin/users/show.html.erb
<div class='container'>
  <div class='row'>
    
    <div class="mx-auto col-sm-12 col-md-8 col-lg-9 my-5">
      <h1>会員ページ</h1>
      
      <div class="text-center mb-3">
        <p class="img-object-fit-radius">
          <%= image_tag @user.get_profile_image(150,150) %>
        </p>
      </div>
      
      <div class="row">
        <div class="col-9 mx-auto">
          <table class='table'>
            <tr>
	            <th>名前</th>
	            <td><%= @user.name %></td>
            </tr>
            <tr>
	            <th>自己紹介</th>
	            <td><%= @user.introduction %></td>
            </tr>
            <tr>
              <th>フォロー</th>
              <td>
                <%= link_to public_user_followings_path(@user) do %> 
                  <%= @follow.count %>
                <% end %>
              </td>
            </tr>
            <tr>
              <th>フォロワー</th>
              <td>
                <%= link_to public_user_followers_path(@user) do %> 
                  <%= @follower.count %>
                <% end %>
              </td>
            </tr>
          </table>
        </div>
      </div>
      
      <div class="my-5">
        <h4>投稿一覧</h4>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>タイトル</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
              <tr>
                <td><%= link_to post.title, post_path(post.id), class: "post_#{post.id}" %></td>
                <td><%= post.genre.name %></td>
                <td>コメント数: <%= post.comments.count %></td>
                <td id="favorite_btn_<%= post.id %>">
                  <%= render "favorites/favorite", post: post %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      
      <div class="my-5">
        <h4>会員ステータス</h4>
        <h5>登録日: <%= @user.created_at.strftime('%Y/%m/%d') %>
          <% if @user.is_deleted %>
            退会済み
            <%= link_to admin_withdrawal_path(@user.id), method: :patch, data: { confirm: 'ステータスを有効にしますか？' }, class: "btn btn-sm btn-success ml-5" do %>
              有効にする <i class="fas fa-user-check"></i>
            <% end %>
          <% else %>
            有効
            <%= link_to admin_withdrawal_path(@user.id), method: :patch, data: { confirm: '本当に退会させますか？' }, class: "btn btn-sm btn-danger ml-5" do %>
              退会させる <i class="fas fa-user-slash"></i>
            <% end %>
          <% end %>
        </h5>
      </div>
    
    </div>
    
  </div>
</div>